spring:
  application:
    name: Product

  datasource:
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: Arman@2004

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis # Specifies the caching provider, e.g., 'redis', 'ehcache', 'caffeine', 'none'
    redis: # Specific properties for Redis cache
      cache-null-values: false
      time-to-live: 60s # Default time-to-live for cache entries in seconds

server:
  port: 8082