spring:
  application:
    name: User

  datasource:
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: Arman@2004

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis
    redis:
      time-to-live: 6000       # TTL = 60 seconds
      cache-null-values: false

jwt:
  secret: YXNkZnNqZGZrc2pkZmtsamZkc2tqZmRsa2Zqc2RmbGtqZg==

#  logging:
#    level:
#      org.springframework.cache: TRACE

server:
  port: 8083


